// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGinDulCr8HLTnAqukihEnFDx6Myx5vRY',
    appId: '1:603970858510:web:5f3c75fbd267f0089c965f',
    messagingSenderId: '603970858510',
    projectId: 'chatapp-559ca',
    authDomain: 'chatapp-559ca.firebaseapp.com',
    storageBucket: 'chatapp-559ca.appspot.com',
    measurementId: 'G-98BFXN1RJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-bzewIqQMWLXXbcwdA-5X-ReC4jE6oLg',
    appId: '1:603970858510:android:be2b895d296762759c965f',
    messagingSenderId: '603970858510',
    projectId: 'chatapp-559ca',
    storageBucket: 'chatapp-559ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRUZs5tccAPwMYFWcE00P_pKvL7pwOe8A',
    appId: '1:603970858510:ios:e0f6b8ba148b884f9c965f',
    messagingSenderId: '603970858510',
    projectId: 'chatapp-559ca',
    storageBucket: 'chatapp-559ca.appspot.com',
    iosClientId: '603970858510-j53f5hgk7u76tdktmlr3h8amfrgfhdbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatWithFirebase',
  );
}
